---
- hosts: aws_ec2
  become: yes
  connection: ssh
  user: ec2-user

  vars:
    ansible_ssh_private_key_file: "/etc/ansible/vivekslavekey.pem"
    ansible_ssh_user: "ec2-user"

  tasks:
    - name: install docker
      command: yum -y install docker

    - name: start docker
      service: name=docker  state=restarted

    - name: status docker
      command: systemctl status docker
